name: 'healthcare_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'healthcare_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  utils_schema: UTILS
  user_name: "dbt_project_user"

on-run-start:
  - "{{ log('Starting dbt run', info=True) }}"
  - "USE SCHEMA {{ target.database }}.{{ var('utils_schema') }}"
  - "create table if not exists {{ target.database }}.{{ var('utils_schema') }}.dbt_audit (model_name string, run_ended_at timestamp)"

models:
  healthcare_dbt:
    +post-hook: |
      insert into {{ target.database }}.{{ var('utils_schema') }}.dbt_audit (model_name, run_ended_at)
      values ('{{ this }}', current_timestamp())
    +database: |
      {%- if target.name in ["default", "ci"] -%}
        HEALTHCARE_AI_DB
      {%- elif target.name == "dev" -%}
        HEALTHCARE_AI_DB
      {%- elif target.name == "prod" -%}
        HEALTHCARE_AI_PROD
      {%- else -%}
        invalid_database
      {%- endif -%}
    +materialized: view

    staging:
      +schema: STG
      +materialized: view
      +tags: ["stg"]

    core:
      +schema: CORE
      +materialized: table
      +tags: ["core"]

    curated:
      +schema: CURATED
      +materialized: view
      +tags: ["mart"]

seeds:
  healthcare_dbt:
    clinic_sites:
      +schema: RAW
      +quote_columns: false

flags:
  require_generic_test_arguments_property: true