env_config:
  default_environment: dev
  environments:
  - name: dev
    env:
      DBT_CURRENT_WH: CORTEX_AI_WH
      DBT_CURRENT_DB: HEALTHCARE_AI_DB
      DBT_CURRENT_SCHEMA: DBT
      DBT_CURRENT_ROLE: CORTEX_AI_DEV
      DBT_CURRENT_USER: "{{ select CURRENT_USER() }}"
      DBT_DATA_INTERVAL_START: "2020-01-01 00:00:00"
      DBT_DATA_INTERVAL_END: "2099-12-31 23:59:59"
  - name: prod
    env:
      DBT_CURRENT_WH: PROD_WH
      DBT_CURRENT_DB: HEALTHCARE_AI_DB
      DBT_CURRENT_SCHEMA: CORE
      DBT_CURRENT_ROLE: ACCOUNTADMIN
      DBT_DATA_INTERVAL_START: "{{ select (DATE_TRUNC('DAY', CURRENT_TIMESTAMP()) - INTERVAL '1 DAY')::string }}"
      DBT_DATA_INTERVAL_END: "{{ select (DATE_TRUNC('DAY', CURRENT_TIMESTAMP()) - INTERVAL '1 SECOND')::string }}"
